[package]
name = "rustymon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"

[dev-dependencies]
reqwest = { version = "0.12.8", features = ["blocking"] }

